### ISSUE TITLE
Version 0.2.2 Release Not Listed on GitHub and Request for User-friendly Changelog

### ISSUE THREAD

**Issue by michaelirey** [ruby/time#10]
It appears that version 0.2.2 has been released, but it is not displayed under the GitHub releases. Currently, only version 0.2.1 is shown as the latest release.

Also, it would be helpful to have a more accessible changelog for users. While it is possible to compare code differences, a traditional changelog would provide a more user-friendly way to understand the updates and changes made in each release.

Thanks!

**Comment by hsbt** [comment]
done https://github.com/ruby/time/releases/tag/v0.2.2
